# Generated by Django 5.0.3 on 2024-03-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(default=0, upload_to='event_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
