# Generated by Django 5.0.3 on 2024-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(default=0, max_length=255, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
