# Generated by Django 5.0.3 on 2024-03-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_author', '0002_customuser_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
    ]
