# Generated by Django 5.0.3 on 2024-03-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_author', '0004_remove_customuser_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
