# Generated by Django 5.0.3 on 2024-03-24 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_remove_event_attendees_event_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_places', models.IntegerField(default=0, verbose_name='Место бронирования')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачиваемый')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('attendees', models.ManyToManyField(related_name='events_attending', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.event', verbose_name='Мероприятие')),
            ],
        ),
    ]
