# Generated by Django 5.0.3 on 2024-03-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
    ]
