# Generated by Django 5.0.3 on 2024-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default=0, max_length=255, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
