# Generated by Django 5.0.3 on 2024-03-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_email_reservation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Подтверждено', 'Подтверждено'), ('Отклонено', 'Отклонено')], max_length=255, verbose_name='Статус'),
        ),
    ]
