# Generated by Django 5.0.3 on 2024-03-31 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_reservation_name_alter_reservation_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='attendees',
        ),
        migrations.AddField(
            model_name='reservation',
            name='attendees',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events_attending', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
            preserve_default=False,
        ),
    ]
