# Generated by Django 5.0.3 on 2024-03-31 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_reservation_user_remove_reservation_attendees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='attendees',
        ),
        migrations.AddField(
            model_name='reservation',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attending', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
