# Generated by Django 5.0.3 on 2024-04-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_remove_reservation_attendees_reservation_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
    ]
